name: valet_parkomate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.4
  audioplayers: ^5.2.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  printing: ^5.12.0
  pdf: ^3.10.6
  cupertino_icons: ^1.0.8
  flutter_swipe_button: ^2.1.2
  camera: ^0.10.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/beep.mp3